name: Buzznauts

channels:
    - nvidia
    - pytorch

dependencies:
    - python=3.8
    - numpy
    - pytorch=1.9
    - torchvision
    - torchaudio
    - cudatoolkit=11.1
    - matplotlib
    - pandas
    - scipy
    - scikit-learn
    - h5py
    - pip
    - pip:
        - watermark
        - opencv-python
        - Pillow
        - nb-clean
        - jupyterlab
        - jupyterlab_vim
        - tqdm
        - ipywidgets
        - duecredit
        - pytest
        - coveralls
        - pytest-cov
        - flake8
        - nilearn
        - decord
        - pyOpenSSL
        - cryptography
        - idna
        - requests
        - torchinfo
        - nltk
        - wandb
